#!/usr/bin/env python3
"""Render wiki/index.md from KG indexes."""
from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
KG = REPO / "kg"
WIKI = REPO / "wiki"

TYPE_LABELS = {
    "exam_topic": "Exam Topics",
    "concept": "Concepts",
    "process": "Processes",
    "structure": "Structures",
    "molecule": "Molecules",
    "enzyme": "Enzymes",
    "term": "Vocabulary Terms",
    "inheritance_pattern": "Inheritance Patterns",
    "experiment": "Experiments",
    "person": "People",
    "disease": "Diseases / Disorders",
    "technique": "Techniques",
    "principle": "Principles",
    "comparison": "Comparisons",
    "chapter": "Chapters",
    "source": "Sources",
}

TYPE_ORDER = list(TYPE_LABELS.keys())


def main() -> None:
    nodes: list[dict] = []
    nodes_dir = KG / "nodes"
    if not nodes_dir.exists():
        raise SystemExit("error: kg/nodes/ does not exist — run build_kg.py first")
    for f in nodes_dir.rglob("*.json"):
        nodes.append(json.loads(f.read_text()))

    by_type: dict[str, list[dict]] = {}
    for n in nodes:
        by_type.setdefault(n["type"], []).append(n)
    for v in by_type.values():
        v.sort(key=lambda n: n["title"].lower())

    by_chapter_idx = json.loads((KG / "indexes" / "by-chapter.json").read_text()) if (KG / "indexes" / "by-chapter.json").exists() else {}
    manifest = json.loads((KG / "manifest.json").read_text()) if (KG / "manifest.json").exists() else {}

    lines: list[str] = []
    lines.append("# Wiki Index — Bio 1320 Exam 3\n")
    lines.append(f"_{manifest.get('node_count', len(nodes))} nodes · "
                 f"{manifest.get('edge_count', 0)} edges · "
                 f"built {manifest.get('built', 'unknown')}_\n")
    lines.append("Auto-generated by `python3 tools/render_index.py`. Do not hand-edit.\n")
    lines.append("See [overview.md](overview.md) for the high-level map.\n")

    # By chapter — most useful for studying
    lines.append("## By Chapter\n")
    chapter_titles = {
        "9": "Chapter 9 — Meiosis",
        "10": "Chapter 10 — Patterns of Inheritance",
        "11": "Chapter 11 — DNA Structure & Replication",
        "12": "Chapter 12 — How Genes Work",
        "13": "Chapter 13 — New Biology",
    }
    for ch in ["9", "10", "11", "12", "13"]:
        ids = by_chapter_idx.get(ch, [])
        if not ids:
            continue
        lines.append(f"### {chapter_titles.get(ch, f'Chapter {ch}')}\n")
        id_to_node = {n["id"]: n for n in nodes}
        ch_nodes = sorted([id_to_node[i] for i in ids if i in id_to_node], key=lambda n: (n["type"], n["title"].lower()))
        for n in ch_nodes:
            rel = Path(n["wiki_path"]).as_posix()
            lines.append(f"- [{n['title']}]({rel.replace('wiki/', '')}) — {n['type']}")
        lines.append("")

    # By type
    lines.append("## By Type\n")
    for t in TYPE_ORDER:
        if t not in by_type:
            continue
        lines.append(f"### {TYPE_LABELS[t]} ({len(by_type[t])})\n")
        for n in by_type[t]:
            rel = Path(n["wiki_path"]).as_posix().replace("wiki/", "")
            summary = (n.get("summary") or "").strip()
            if len(summary) > 140:
                summary = summary[:137] + "…"
            lines.append(f"- [{n['title']}]({rel}) — {summary}" if summary else f"- [{n['title']}]({rel})")
        lines.append("")

    (WIKI / "index.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote wiki/index.md ({len(nodes)} nodes)")


if __name__ == "__main__":
    main()
